#KOD SAYFASI UZERINDE; # SEMBOLUNU KOD SATIRINDA ILK KARAKTER OLARAK KULLANIP NOT ALABILIRIZ.

#####SAYILAR, DEGERLER#####
#KESIKLI DEGER.
9
print(9)

#SUREKLI DEGER.
9.47
print(9.47)

#ISLEMLER.
9-5
9+5
9*5
9/5
9/5*2.1

1.04*3.54
#ONDALIK OLARAK ISLEM GERCEKLESTIRIR.


9**3
#9 UN 3. KUVVETI OLARAK ISLEM GERCEKLESTIRIR.

9%3
#9 UN 3. E GORE MOD ISLEMINI GERCEKLESTIRIR.

#####KARAKTER VE METIN IFADELERI#####
#AYNI FORMAT CIKTISI. EN-TR KARAKTER ORNEGI.
'MERHABA MIRAC'
'MERHABA MİRAÇ'
"MERHABA MIRAC"
"MERHABA MİRAÇ"

#CONSOLE CIKTISI ISTENDIGINDE ZORUNLU YAZDIRMA ISLEMI GEREKMEKTEDIR.
#EN-TR KARAKTER ORNEGI.
print('MERHABA MIRAC')
print('MERHABA MİRAÇ')
print("MERHABA MIRAC")
print("MERHABA MİRAÇ")


#KIMI DURUMLARDA FONKSIYONEL ISLEM CIKTILARINI KESTIREMEYEBILIRIZ.
#type() FONKSIYONU BU DURUMLAR ICIN KULLANILABILIR.
type(9-5)
type(9+5)
type(9*5)
type(9/5)
type(9/5*2.1)

type('MERHABA MIRAC')
type('MERHABA MİRAÇ')
type("MERHABA MIRAC")
type("MERHABA MİRAÇ")

type('9')
type("9")


#####TEMEL ISLEMLER VE FARKLI CIKTILAR#####
"a" + "b"
'a' + 'b'
'a' + ' b'
#HATA VERMEZ, IKI IFADEYI BIRLESTIREREK YAZAR.

"a" - "b"
'a' - 'b'
#HATA VERIR, MATEMATIKSEL ISLEM OLARAK ALGILAR.

print('a' + 'b')
print("a" + "b")
print('a' + ' b')
print("a" + " b")

"a"*3
'a'*3
#HATA VERMEZ, IFADEYI n kere YAZAR.

"a"%3
'a'%3
#HATA VERIR, MATEMATIKSEL ISLEM OLARAK ALGILAR.
