#BAZI VERI KUMELERI VE ALGORITMIK ISLEMLERDE BASIT COZUMLER ADINA HAZIR FONKSIYONLARA IHTIYAC DUYABILIRIZ.
#BUNLARDAN POPULER OLAN BIRKACINA GOZ ATALIM.


#ATAMALAR - DEGISKENLER
a=9
b=2
a*b


#DEL ILE GECMIS PARAMETRIK KULLANIMLARI SILEBILIRIZ.
del a
del b


#LEN() FONKSIYONU ILE KARAKTER (STRING) DEGERLERIN KARAKTER SAYISINA ULASABILIRIZ.
mz="Yasasin Cumhuriyet!" 
len(mz)

c=1
d=2
len(c*d)
#HATA VERIR, SAYISAL IFADE CIKTILARININ SONUCLARINDA UZUNLUK FONKSIYONU KULLANILAMAZ.


#UPPER() FONKSIYONU ILE KARAKTER (STRING) DEGERLERIN KARAKTERLERINI BUYUK HARF SEKLINDE KULLANABILIRIZ.
mz.upper()


#LOWER() FONKSIYONU ILE KARAKTER (STRING) DEGERLERIN KARAKTERLERINI KUCUK HARF SEKLINDE KULLANABILIRIZ.
mz.lower()