#BAZI VERI KUMELERI VE ALGORITMIK ISLEMLERDE BASIT COZUMLER ADINA HAZIR FONKSIYONLARA IHTIYAC DUYABILIRIZ.
#BUNLARDAN POPULER OLAN BIRKACINA GOZ ATALIM.

mz="Yasasin Cumhuriyet!" 


#ISLOWER() FONKSIYONU ILE KARAKTER (STRING) DEGERLERIN KARAKTERLERINI KUCUK HARF OLUP-OLMADIGINI KONTROL EDEBILIRIZ.
mz.islower()


#ISUPPER() FONKSIYONU ILE KARAKTER (STRING) DEGERLERIN KARAKTERLERINI BUYUK HARF OLUP-OLMADIGINI KONTROL EDEBILIRIZ.
mz.isupper()


#CAPITALIZE() FONKSIYONU ILE KARAKTER (STRING) DEGERLERIN ILK KARAKTERLERINI BUYUK HARF SEKLINDE KULLANABILIRIZ.
mz.capitalize()
mz.lower().capitalize()
mz.upper()().capitalize()


#REPLACE() FONKSIYONU ILE KARAKTER (STRING) DEGERLERIN BELIRLI KARAKTERLERINI DEGISTIRIP YENI/DUZENLENMIS BIR PARAMETRE OLUSTURABILIRIZ.
mz_new=mz.replace("!", "!!!")

print(mz_new)
