#BAZI VERI KUMELERI VE ALGORITMIK ISLEMLERDE BASIT COZUMLER ADINA HAZIR FONKSIYONLARA IHTIYAC DUYABILIRIZ.
#BUNLARDAN POPULER OLAN BIRKACINA GOZ ATALIM.

mz=" Yasasin Cumhuriyet! " 


#STRIP() FONKSIYONU ILE BELIRLI BIR KARAKTERE (STRING) GORE KIRPMA ISLEMI GERCEKLESTIREBILIRIZ.
mz_new=mz.strip()
print(mz_new)
#BOSLUK KARAKTERI ICIN ISLEMDE BULUNDUK.VARSAYILAN DEGER OLARAK BOSLUK KARAKTERI KULLANILMAKTADIR.


mz.rstrip()
#SAGDAN BOSLUK KARAKTERI ICIN ISLEMDE BULUNDUK.
mz.lstrip()
#SOLDAN BOSLUK KARAKTERI ICIN ISLEMDE BULUNDUK.


#FARKLI KARAKTERLERE YONELIKTE STRIP() FONKSIYONU DINAMIK BIR SEKILDE KULLANILABILIR.
new_mz="*Yasasin Cumhuriyet*" 
new_mz.strip("*")
#* KARAKTERI ICIN ISLEMDE BULUNDUK.


#FIND() FONKSIYONU ILE BELIRLI BIR KARAKTERE ARAMASI VE SAYDIRMASI ISLEMI GERCEKLESTIREBILIRIZ.
mz.find("as")
#-1 DEGERINI DONMESI DURUMUNDA KARAKTERIN BULUNMADIGINI IFADE EDER.

mz.find("as",0,4)
#0-4 BASLANGIC VE BITIS KARAKTER ARALIGI.


#DIR() ILE EK METINSEL IFADE FONKSIYONLARINA GOZ ATABILIRIZ.
dir(mz)