#ALGORITMIK OLARAK IFADELERIN (DEGERLERIN) KIMI ZAMAN DILIMLERINDE YENIDEN GRUPLANIP/KUMELENIP KULLANILMASI GEREKEBILIR.
#ALT KUME, KUMELEME ISLEMLERI - SUBSTRING


mz=" Yasasin Cumhuriyet! " 


mz[0]
#N.CI ELEMAN TERCIHLERI YAPISAL OLARAK INDEKS MANTIGI ILE CALISMAKTADIR.
#0.CI ELEMAN ASLINDA IFADENIN ILK KARAKTERIDIR.
#0.CI ELEMAN=" "=BOSLUK KARAKTERI.


mz[4]
#a


mz[25]
#IndexError: string index out of range
#MEVCUT KARAKTER IFADESINDE YER ALMAYAN INDEKS BASAMAK HATASI.


#BAZI GEREKCELI DURUMLAR ICIN BELIRLI BIR INDEKS ARALIGINDAKI IFADELER GEREKEBILIR.
mz[0:6]
#0.CI INDEKS DAHIL 6.CI YA KADAR OLAN KARAKTERLERI SECELIM.
#' Yasas'


mz[:6]
#ILK BASLANGIC INDEKSI BOS BIRAKILIRSA 0.CI INDEKS OLARAK KARAKTER SECIMI GERCEKLESTIRILIR.
#' Yasas'


#MEVCUT IFADENIZDE SONDAN BASLAYARAK GERIYE DOGRU KARAKTER SECIMI GERCEKLESTIRMEK ISTERSENIZ INDEKS - IFADELERI OLMALIDIR.
mz[-2]
#!


mz[-9:-4]
#SONDAN 4.CI ELEMAN ILE 9.CU ELEMANDA KADAR OLAN KARAKTERLERI SECELIM.
#huriy