#CESITLI ALGORITMIK ISLEMLERDE ARD-ARDA/SUREKLI YA DA KISMI KULLANIM DURUMLARI ADINA GIRDI 
#OLUSTURAN DEGERLERIN KULLANIMINI KOLAYLASTIRMAK ICIN "DEGISKENLER" KULLANILMAKTADIR.


#DEGISKEN ATAMA MANTIGI ISE; SAGDAN SOLA DOGRU GERCEKLESMEKTEDIR.
mz_text=" Yasasin Cumhuriyet! " 
mz_text_ek="29 Ekim 1923"
mz_int=1923


print(mz_text_ek+' - '+mz_text)
print(str(mz_int) +' '+mz_text)


#DEGISKENLERIMIZ ICERISINDE EK DEGISKEN YA DA GELECEK BIR PARAMETRIK ALAN DEGERI EKLEYEBILIRIZ.
x=3
y=5


mz_parameter=(5+x)
print(mz_parameter)
type(mz_parameter)


mz_math_complex=x**(y**2)
print(mz_math_complex)
type(mz_math_complex)


#KIMI ALGORITMIK SURECLERDE DISARDAN KULLANICI TARAFINDAN DEGER GIRILMESI GEREKEBILIR.
#BUNUN ICIN INPUT() FONKSIYONU KULLANILMAKTADIR.
x1=input()
x2=input()


y=x1+x2
#y= IFADESI GIRILEN IKI DEGERI YAN YANA YAZACAKTIR.
#CUNKU INPUT() FONKSIYONU KULLANICI TARAFINDAN GIRILEN DEGERLERI METINSEL OLARAK ELE ALMAKTADIR.


y=int(x1)+int(x2)
#INT() TIP DONUSUMU ILE GIRILEN DEGERLERE YONELIK MATEMATIKSEL ISLEM GERCEKLESTIRILEBILECEKTIR.


y=(x1**x2)-(x1.x2)
#TIP DONUSUMU YAPILMADIGI TAKDIRDE HATA VERECEKTIR.


y=float(x1)+float(x2)
#GIRILEN IFADEYI FLOAT() ILE ONDALIK DEGERE DONUSTUREBILIRIZ.
#FAKAT GIRILEN IFADE INT() KALIBINDA ISE VIRGUL SONRASI 0 OLARAK GORUNTULENECEKTIR.


x3=13.949999988079071
#ONDALIK SAYILARA YONELIK CESITLI FORMATLAMA ISLEMINDE BULUNALIM.


print("%.2f" % x3)
#13.95


a=round(x3,2) #CIKTI 13.95, DEGISKEN ATAMASI 13.95.
print(a)


b=print("%.2f" % round(x3, 2)) #CIKTI 13.95, DEGISKEN ATAMASI NONE.
print(b)
#NONE


c=print("{:.2f}".format(x3)) #CIKTI 13.95, DEGISKEN ATAMASI NONE.
print(c)
#NONE


a==b
a==c
#KARSLIKLI OLARAK DEGERLERIN BIRBIRINE ESIT OLUP OLMADIGINI == OPERATORU YARDIMI ILE KONTROL EDELIM.
#FALSE

b==c
#TRUE


print("{:.5f}".format(round(x3, 2)))
#CIKTI 13.95000


print("{:.15f}".format(round(x3, 2)))
#CIKTI 13.949999999999999


y=str(x1)
#GIRILEN IFADEYI STR() ILE METIN DEGERINE DONUSTUREBILIRIZ.
#GIRILEN TUM IFADELERDE BU DONUSUM UYGULANABILIR.


y=str(x1)+str(x2)
#IKI IFADEYI YAN YANA YAZACAKTIR.