#ANALIZ VE KONTROL SURECLERINDE ARALIKLI OLARAK VERIYI GORUNTULEMEK VE CIKTILARA ANLAM KAZANDIRIP OKUNULABILIRLIK SAGLAMAK GEREKEBILIR.
#BU COZUMLEMELER ICIN PRINT() FONKSIYONU KULLANILMAKTADIR.


mz="Yasasin Cumhuriyet!"  
mz_gelecek="1923" 
mz_kahraman="M.K.A"


#DOGRUDAN CIKTI OLARAK KONTROL ETMEK ICIN PARAMETREYI SATIR BAZLI CALISTIRIP GORUNTULEMEDE BULUNABILIRIZ.
mz


print(mz)
#YANI SIRA PRINT() FONKSIYONU ILE DE CIKTI ELDE EDEBILIRIZ.


print(mz,mz_gelecek)
#Yasasin Cumhuriyet! 1923 OTOMATIK OLARAK BIR BOSLUK ILE AYIRMAKTADIR.


print(mz + mz_gelecek)
#PRINT() FONKSIYONU ICERISINDE + ILE IFADE BIRLESTIRMASI KULLANILDIGINDA VARSAYILAN BOSLUK DEGERI OLMADAN CIKTI ALIRIZ.
#Yasasin Cumhuriyet!1923


print(mz + ' ' + mz_gelecek + ' ' + 'M.K.A.')
#' ' ARGUMANI/AYRACI ILE IFADELER ARASINDA BOSLUK KULLANICI INSIYATIFINDE KULLANILABILIR.
#Yasasin Cumhuriyet! 1923 M.K.A.


print(mz,mz_gelecek, sep=" / ")
#Yasasin Cumhuriyet! / 1923 "/" AYRACI ILE AYRILACAKTIR.
# sep="" ARGUMAN OLARAK IFADE EDILMEKTEDIR.
#PRINT() FONKSIYONUNDA VARSAYILAN/ON TANIMLI OLARAK " " BOSLUK OLARAK KULLANILMAKTADIR.


#BIRDEN COK METINSEL IFADE BELIRLENECEK AYRAC ILE BIRLESTIRILEBILIR.
print(mz,mz_gelecek,mz_kahraman, sep=" / ")
#Yasasin Cumhuriyet! / 1923 / M.K.A CIKTISINI ELDE EDECEGIZ.


print(mz,mz_kahraman, sep='\n')
#sep='\n' ILE IFADELERINI ALT ALTA YAZARAK AYIRIR.
#Yasasin Cumhuriyet!
#M.K.A

?print
#? VE FONKSIYON ADI CALISTIRILDIGINDA KULLANIMI HAKKKINDA IPYTHON CONSOLE UZERINDE ACIKLAMA BILGISI VERILMEKTEDIR. 
#Docstring:
#print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)


#end="" ARGUMANI ILE SON IFADEDEN SONRA GENEL IFADE SONUNA @ KARAKTERI EKLENIR. 
print(mz,mz_gelecek, sep=" / ", end="@")


print(mz,'M.K.A', 1923)
#BIRBIRINDEN BAGIMSIZ VERI TIPLERINI DOGRUDAN CIKTI OLARAK BU YONTEM ILE KULLANABILIRIZ.


print(mz +'M.K.A'+ 1923)
#BU YONTEMDE ISE HATA ALIRIZ.
#TypeError: can only concatenate str (not "int") to str


#FARKLI FORMATLARDA DA CIKTI ALMAMIZ MUMKUN.
print(*[mz, 1923, 'SANLI TARIH.'])
#Yasasin Cumhuriyet! 1923 SANLI TARIH.


#YAZDIRMA ISLEMINI DOSYA OKUMA ILE DE GERCEKLESTIREBILIRIZ.
import time
dosya=open('cumhuriyet.txt', 'r')
dosya_oku=dosya.read()
baslangic=time.time()
print(dosya_oku,flush=False)
bitis=time.time()
print(bitis-baslangic)