#FARKLI ZAMAN DILIMLERINDE, MEVCUT CALISMALARIMIZDA FARKLI VERI TIPLERINI BIR ARADA
#DEGISTIRILEBILIR VE YINELEMELI OLARAK KULLANMAMIZ GEREKEBILIR.
#BU NOKTADA LISTELER KULLANILMAKTADIR.

#LISTE GOSTERIM VE KULLANIM FORMATI;
#[]
#list()


cumhuriyet=["Yasasin","Cumhuriyet"]
deger=[1881,1923]
varlik_nesne=[1881,1923,"Yasasin","Cumhuriyet",9.5]


cumhuriyet[1]
#LISTENIN N.CI ELEMANI.
#CALISMA MANTIGI INDEKS ILE AYNI.


varlik_nesne[0:3]
#LISTENIN M-N.CI ELEMANLARININ SECIMI.
#SOL/ILK DEGER BOS BIRAKILDIGINDA 0.CI INDEKS OLARAK ALGILAR.


varlik_nesne[:3]
#BASTAN 3.CU ELEMANA KADAR.
varlik_nesne[3:]
#3.CU ELEMANDAN SON ELEMANA KADAR.


karmasik_nesne=[cumhuriyet,deger,varlik_nesne,"Python",3.14]
#[['Yasasin', 'Cumhuriyet'], [1881, 1923], [1881, 1923, 'Yasasin', 'Cumhuriyet', 9.5], 'Python', 3.14]


karmasik_nesne[1][1]
#ILK LISTENIN 1.CI INDEKSLI ELEMANINI SECER,
#SECIM BIR LISTE ISE; O LISTENINDE 1.CI INDEKSLI ELEMANINI SECER.
#BU ISLEM BILINEREK YAPILMAKTADIR. (RASTGELELIK SADECE TEST ICIN OLMALIDIR.) 


varlik_nesne
varlik_nesne[4]="Sonsuz"
#LISTE UZERINDE N.CI ELEMANI DEGISTIRMEK ISTEDIGIMIZDE; ELAMANI BULUP,
#PARAMETRE ATAMASI GIBI ELEMANA DEGER ATAMAKTAYIZ.
varlik_nesne


varlik_nesne[0:2]="Yeni","Deger"
#BIRDEN COK DEGERE YONELIK ATAMA ISLEMI GERCEKLESTIRILECEGI DURUMDA ISE;
#ELEMANLAR LSITELENME MANTIGI GIBI SECILIP, SIRALI OLARAK DEGERLERI ATANMALIDIR.


varlik_nesne=varlik_nesne + ["M.K.A."]
#LISTEYE BIR ELEMAN EKLEMEK ISTEDIGIMIZDE VE KALICI OLARAK MEVCUT LISTEDE OLMASINI ISTEDIGIMIZ DURUMDA
#ILGILI LISTEYE ELEMANI EKLEYEREK AYNI ISIMDEKI LISTEYE ATAMAMIZ GEREKMEKTEDIR.
varlik_nesne


del varlik_nesne[2]
#LISTE ICERISINDEKI BIR ELEMANI LISTEDEN SILMEK ICIN ISE
#DEL KOMUTU VE ELEMANIN LISTEDEKI ILGILI INDEKSI GEREKMEKTEDIR.


type(cumhuriyet)
type(deger)
type(varlik_nesne)
type(karmasik_nesne)


type(karmasik_nesne[0])
#0=LIST

type(karmasik_nesne[3])
#3=STR

type(karmasik_nesne[4])
#4=FLOAT


len(cumhuriyet)
#2=IKI NESNE VAR.

len(karmasik_nesne)
#5=IKI NESNE, 3 LISTE VAR.


liste=[1,2,3,4,5]
liste.reverse()
#REVERSE() FONKSYIONU ILE LISTEYI TERSTEN LISTELEYEBILIRIZ.
liste


liste.append(6)
liste
#APPEND() FONKSYIONU ILE LISTEYE BELIRLEDIGIMIZ BIR ELEMANI EKLEYEBILIRIZ.
#"+" KOMUTUNA ALTERNATIF OLARAK.
