#FARKLI ZAMAN DILIMLERINDE LISTELER UZERINDE CESITLI ISLEMLERDE BULUNULMAKTADIR.
#BU NOKTADA METODLAR COZUM SAGLAMAKTADIR.
#!!!LISTELER DEGISTIRILABILIR OZELLIKTE OLDUGU ICIN BU ISLEMLERDE BULUNABILMEKTEYIZ.!!!

#LISTE FORMATLARI UZERINDE ORNEKLERDE BULUNALIM;
#[]
#list()


cumhuriyet=["Yasasin","Cumhuriyet"]
deger=[1881,1923]
varlik_nesne=[1881,1923,"Yasasin","Cumhuriyet",9.5]


#APPEND() METODU/FONKSIYONU ILE LISTEYE BELIRLEDIGIMIZ BIR ELEMANI EKLEYEBILIRIZ.
#"+" KOMUTUNA ALTERNATIF OLARAK.
varlik_nesne.append("!")
varlik_nesne
#[1881, 1923, 'Yasasin', 'Cumhuriyet', 9.5, '!']


parametre="Parametre"
varlik_nesne.append(1919)
varlik_nesne.append(9.00)
varlik_nesne.append(parametre)
varlik_nesne
#[1881, 1923, 'Yasasin', 'Cumhuriyet', 9.5, '!', 1919, 9.0, 'Parametre']


#INSERT() METODU/FONKSIYONU ILE LISTEYE BELIRLEDIGIMIZ BIR ELEMANI INDEKS BAZLI EKLEYEBILIRIZ.
varlik_nesne.insert(0,"!")
varlik_nesne
#['!', 1881, 1923, 'Yasasin', 'Cumhuriyet', 9.5, '!', 1919, 9.0, 'Parametre']


#INSERT() METODU/FONKSIYONU ILE DINAMIK BIR SEKILDE SON ELEMAN OLACAK FORMATTA
#LISTEYE BELIRLEDIGIMIZ BIR ELEMANI INDEKS BAZLI EKLEYEBILIRIZ.
varlik_nesne.insert(len(varlik_nesne),"Son Eleman")
varlik_nesne


#POP() METODU/FONKSIYONU ILE LISTEDEN INDEKS BAZLI BIR ELEMANI CIKARTABILIRIZ.
varlik_nesne.pop(0)
varlik_nesne
#['!']
#[1881, 1923, 'Yasasin', 'Cumhuriyet', 9.5, '!', 1919, 9.0, 'Parametre','Son Eleman']


#REMOVE() METODU/FONKSIYONU ILE LISTEDEN BILDIGIMIZ BIR ELEMANI CIKARTABILIRIZ.
varlik_nesne.remove("!")
varlik_nesne
#[1881, 1923, 'Yasasin', 'Cumhuriyet', 9.5, 1919, 9.0, 'Parametre']


#CLEAR() METODU/FONKSIYONU ILE LISTEDEKI ELEMANLARI TAMEMEN CIKARTABILIRIZ.
#TUM ELEMANLARI SILMEK GIBI DUSUNULEBILIR, LISTEYI BOSALTMAK.
varlik_nesne.remove("!")
varlik_nesne
#[1881, 1923, 'Yasasin', 'Cumhuriyet', 9.5, 1919, 9.0, 'Parametre']


#COPY() METODU/FONKSIYONU ILE BELIRLEDIGINIZ BIR LISTEYI ISLEMLER ARASINDA YEDEKLEYEBILIRSINIZ.
varlik_nesne_yedek=varlik_nesne.copy()
varlik_nesne_yedek
#[1881,1923,'Yasasin','Cumhuriyet',9.5,1919,9.0,'Parametre','Son Eleman']


#EXTEND() METODU/FONKSIYONU ILE BELIRLEDIGINIZ BIR LISTEYE KALICI OLARAK ELEMAN EKLEYEBILIRIZ.
varlik_nesne.extend(["-1881-",18,"Samsun"])
ek_liste=["Ek Liste","Yeni Liste"]
varlik_nesne.extend(ek_liste)
varlik_nesne
#[1881,1923,'Yasasin','Cumhuriyet',9.5,1919,9.0,'Parametre','Son Eleman',1919,'-1881-',18,'Samsun','Ek Liste','Yeni Liste']


#COUNT() METODU/FONKSIYONU ILE LISTEDE BILDIGIMIZ BIR ELEMANDAN KAC TANE BULUNDUGUNU BULABILIRIZ.
varlik_nesne.count("Cumhuriyet")
#1
varlik_nesne.append(1919)
# 1919 ♥ IKI KERE EKLENDI.
varlik_nesne.count(1919)
#3


#INDEX() METODU/FONKSIYONU ILE LISTEDE BILDIGIMIZ BIR ELEMANIN HANGI INDEKSTE BULUNDUGUNU BULABILIRIZ.
varlik_nesne.index(1881)
#5


#REVERSE() METODU/FONKSIYONU ILE LISTEYI TERSINE CEVIREBILIRIZ.
#INDEKS BAZLI OLARAK DUSUNULMESI GEREKMEKTEDIR.
varlik_nesne.reverse()


#SORT() METODU/FONKSIYONU ILE LISTEYI SAYISAL DEGERLERE YONELIK SIRALAYABILIRIZ.
#!!!LISTEDEKI ELEMANLAR SAYISAL DEGERDE OLMALIDIR.!!!
varlik_nesne.sort()


#MAX() METODU/FONKSIYONU ILE LISTENIN EN BUYUK DEGERLI ELEMANINI BULABILIRSINIZ.
#!!!LISTEDEKI ELEMANLAR SAYISAL DEGERDE OLMALIDIR.!!!
varlik_nesne.max()


#MIN() METODU/FONKSIYONU ILE LISTENIN EN KUCUK DEGERLI ELEMANINI BULABILIRSINIZ.
#!!!LISTEDEKI ELEMANLAR SAYISAL DEGERDE OLMALIDIR.!!!
varlik_nesne.min()