#FARKLI ZAMAN DILIMLERINDE FARKLI VERI YAPILARINA YONELIK ISLEM GERCEKLESTIRMEMIZ GEREKEBILIR.
#BU NOKTADA SET (KUME VB.) COZUM SAGLAMAKTADIR.

#SET (KUME) FORMATLARINDA ELEMANLAR YAPISAL SIRASIZDIR, ESSIZDIR, DEGISTIRILEBILIRDIR.
#ESSIZDIR=BIRDEN COK AYNI DEGERI TEK OLARAK KUMELEYECEKTIR.
#S=set()

liste=[1923,"Cumhuriyet"]

kume = set(liste)
print(kume)
#{'Cumhuriyet', 1923}

ek_liste= ["Yasasin"]

yeni_kume = set(ek_liste)
print(yeni_kume)

dir(yeni_kume)
#HANGI YONTEMLER/ISLEMLER UYGULANABILIR.

yeni_kume.add("ek_eleman")
#KUMEMIZE ELEMAN EKLEMEK ICIN KULLANILIR.
print(yeni_kume)

yeni_kume.remove("ek_eleman")
#KUMEMIZDE YER ALAN ELEMANI SILMEK ICIN KULLANILIR.
#EGER ELEMAN YOK ISE HATA DONER.
print(yeni_kume)

yeni_kume.discard("ek_eleman")
#KUMEMIZDE YER ALAN ELEMANI SILMEK ICIN KULLANILIR.
#EGER ELEMAN YOK ISE HATA DONMEZ.
print(yeni_kume)

kume1=set([1,2,3])
kume2=set([3,4,5])

kume1.difference(kume2)
#IKI KUME ARASINDAKI FARKLI ELEMANLARI BULMAK ICIN KULLANILIR.

kume1.symmetric_difference(kume2)
#IKI KUME ARASINDAKI SIMETRIK FARKLI ELEMANLARI BULMAK ICIN KULLANILIR.

kume1-kume2
kume2-kume1
#IKI KUME ARASINDAKI FARKLI ELEMANLARI BULMAK ICIN KULLANILIR.

kume1.intersection(kume2)
#IKI KUMENIN ORTAK ELEMANINI VERMEKTDIR.
#BUNU EK OLARAK SU SEKILDE DE YAPABILIRIZ;
kume1 & kume2

kume1.union(kume2)
#IKI KUMEYI BIRLSTIRMEK ICIN KULLANILIR.

kume3=set([1,2,3])
kume4=set([1,2,3,4,5])

kume3.isdisjoint(kume4)
#IKI KUMENIN KESISIMININ BOS KUME OLUP OLMADIGINI SORGULAMAK ICIN KULLANILIR.
#KESISIMI VAR MI?
#False / VAR DEMEK --- True / YOK DEMEK

kume3.issubset(kume4)
#ALT KUME DURUMUNU SORGULAMAK ICIN KULLANILIR.
#kume3, kume4'UN ALT KUMESI MIDIR?
#True / EVET DEMEK --- False / HAYIR DEMEK

kume3.issuperset(kume4)
#KAPSAMA DURUMUNU SORGULAMAK ICIN KULLANILIR.
#kume3, kume4'U KAPSAR MI?
#False / HAYIR DEMEK --- True / EVET DEMEK 